### ISSUE TITLE
Using Iridium

### ISSUE THREAD

**Issue by anschwa** [puffnfresh/iridium#1]
I think this is a really awesome project, however, after building with `idris --build iridium-quartz.ipkg`and running with `./iridium`, how do I use iridium? What are the default keybindings (are there any)? Thanks.

**Comment by puffnfresh** [comment]
Sorry, there isn't any documentation because it's not extremely useful at the moment. The keys are listed here:

https://github.com/puffnfresh/iridium/blob/master/src/Quartz.idr#L126-L133

I sadly is defined in terms of OS X virtual key codes, this needs to be fixed but for now:

```
space   49
j       38
k       40
```

Command + Option is the meta key, press that plus one of the above keys. Holding Shift when changing focus will move a window.

**Comment by anschwa** [comment]
Excellent, thanks. I think this project is absolutely amazing. I need to get more familiar with Idris because I'd love to start contributing.

**Comment by JasonJAyalaP** [comment]
- 1
  I've been using amethyst, but this project has the potential to be the best (tiling) window manager for OS X.
